
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/kubernetestest-1338/hello-node:v1
        name: web
        ports:
        - containerPort: 8080
          name: http-server
